school/Controllers/EstudiantesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using School.Models;
using Microsoft.EntityFrameworkCore;

namespace School.Controllers
{
    public class EstudiantesController : Controller
    {
        public EstudiantesController(ModelSchool context)
        {
            _context = context;
        }

        private readonly ModelSchool _context;
        public IActionResult Index()
        {
            var students = _context.People
                                .Where(r => r.HireDate == null)
                                .ToList();
            return View(students);
        }

        
        public IActionResult Ficha(int id) 
        {
            var student = _context.People
                                .Where(r => r.PersonID == id)
                                .FirstOrDefault();
            return View(student);
        }

        public IActionResult Nuevo() {
            return View("Ficha", new Person());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Nuevo(Person student) {
            if(ModelState.IsValid)
            {
                _context.People.Add(student);
                _context.SaveChanges();
                return RedirectToAction("index");
            }
            else 
            {
                return View("Ficha", new Person());
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Ficha(int id, Person student) 
        {
            if(id != student.PersonID) return NotFound();

            if(ModelState.IsValid)
            {
                _context.Update(student);
                _context.SaveChanges();

                return RedirectToAction("Index");
            } else 
            {
                return View(student);
            }
        }


    }
}

school/Views/Estudiantes/Ficha.cshtml
@model Person

@{
    var controller = ViewContext.RouteData.Values["controller"].ToString().ToLower(); 
    var action = ViewContext.RouteData.Values["action"].ToString().ToLower();         

}

<br />
<div class="row">
    <div class="col">
        <h1>Ficha de Estudiante</h1>
        <hr />
        <br />
    </div>
</div>
<form method="post">     
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    @if(action == "nuevo")
                    {
                        <h4><b>Nuevo Estudiante</b></h4>
                    }
                    else
                    {
                        <h4><b>@Model.FirstName @Model.LastName</b></h4>
                    }                    
                </div>
                <div class="card-body">
                     @if(action == "nuevo")
                    {
                        <input type="hidden" class="form-control" asp-for="PersonID" />
                    }
                    else
                    {
                        <div class="form-group row mb-2">
                            <label asp-for="PersonID" class="col-sm-2 col-form-label"></label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" asp-for="PersonID" />
                            </div>
                        </div>
                    }   

                    <div class="form-group row mb-2">
                        <label asp-for="FirstName" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" asp-for="FirstName" />
                            <span asp-validation-for="FirstName" class="text-danger"></span>
                        </div>
                    </div>
                    

                     <div class="form-group row mb-2">
                        <label asp-for="LastName" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" asp-for="LastName" />
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>
                    </div>

                     <div class="form-group row mb-2">
                        <label asp-for="EnrollmentDate" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <input asp-format="{0: dd/MM/yyyy}" type="text" class="form-control" asp-for="EnrollmentDate" />
                        </div>
                    </div>    
                </div>
            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-6">
            <a asp-controller="Estudiantes" asp-action="Index" class="btn btn-success">Volver</a>
        </div>
        <div class="col-6 text-end">
            <input type="submit" class="btn btn-primary" value="Grabar" />
        </div>
</form>

school/Views/Estudiantes/Index.cshtml
@model List<Person>

@section Scripts {
    <script type="text/javascript">        
        $(document).ready(function() { 
             App.Page.Students.List.OnLoad();
        });      
    </script>
}

<div class="row">
    <div class="col">
        <h1>Listado de Estudiantes</h1>
        <hr />
    </div>
</div>
<div class="row">
    <div class="col">
        <table id="estudiantes" class="table table-striped">
            <thead>
                <tr>
                    <th><b>ID</b></th>
                    <th><b>Nombre</b></th>
                    <th><b>Apellido</b></th>
                    <th><b>Fecha de alta</b></th>
                </tr>
            </thead>
            <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td><a asp-controller="Estudiantes" asp-action="Ficha" asp-route-id="@item.PersonID">@item.PersonID</a></td>
                    <td>@item.FirstName</td>
                    <td>@item.LastName</td>
                    <td>@item.EnrollmentDate.GetValueOrDefault().ToShortDateString()</td>
                </tr>
            }                
            </tbody>
        </table>
    </div>
</div>

<div class="row">
    <div class="col">
        <a asp-controller="Estudiantes" asp-action="Nuevo" class="btn btn-success">Añadir estudiante</a>
    </div>
</div>